Asp.Net.MVC5_TatilSeyehatSitesi/Controllers/TravelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Asp.Net.MVC5_TatilSeyehatSitesi.Models;
using PagedList;
using PagedList.Mvc;

namespace Asp.Net.MVC5_TatilSeyehatSitesi.Controllers
{
    public class TravelController : Controller
    {
        TatilSeyehatMVC5Entities db = new TatilSeyehatMVC5Entities();
        TableList data = new TableList();
        // GET: Travel
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            data.TravelList = db.TBLTRAVELS.Where(x => x.STATUS == true).OrderByDescending(x => x.DATE).ToPagedList(pageNumber, pageSize);
            data.TravelComment = db.TBLTRAVELCOMMENTS.Where(x => x.STATUS == true).ToList();
            return View(data);
        }

        public ActionResult TravelDetail(int id)
        {
            data.Travel = db.TBLTRAVELS.Where(x => x.ID == id).ToList();
            return View(data);
        }

        public PartialViewResult TravelRightSideBar()
        {
            data.Travel = db.TBLTRAVELS.Where(x => x.STATUS == true).ToList();
            data.TravelComment = db.TBLTRAVELCOMMENTS.Where(x => x.STATUS == true).ToList();
            return PartialView(data);
        }

        public PartialViewResult Comments(int id)
        {
            data.TravelComment = db.TBLTRAVELCOMMENTS.Where(x => x.TRAVELSID == id && x.STATUS == true).ToList();
            return PartialView(data);
        }

        [HttpGet]
        public PartialViewResult Comment(int id)
        {
            ViewBag.TravelID = id;
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult Comment(TBLTRAVELCOMMENTS AddCdomment)
        {
            try
            {
                AddCdomment.DATE = DateTime.Now;
                AddCdomment.STATUS = false;
                db.TBLTRAVELCOMMENTS.Add(AddCdomment);
                db.SaveChanges();
                TempData["success"] = "Yorumunuz Admin tarafından kontrol edilip ona göre yayına alınacaktır.";
                return PartialView();
            }
            catch (Exception)
            {
                TempData["error"] = "Yorumunuz eklenirken bir hata oluştu. Lütfen tekrar deneyiniz.";
                return PartialView();
            }

        }
    }
}

Asp.Net.MVC5_TatilSeyehatSitesi/Views/Travel/Comment.cshtml
<form method="post">
    <input type="hidden" name="TRAVELSID" value="@ViewBag.TravelID" required />
    <input type="text" placeholder="Ad Soyad" name="USERNAME" required />
    <input type="text" placeholder="Mail" name="MAIL" required />
    <textarea placeholder="Mesaj" name="COMMENT"></textarea>
    <input type="submit" value="Gönder" />
</form>

Asp.Net.MVC5_TatilSeyehatSitesi/Views/Travel/Comments.cshtml
@using Asp.Net.MVC5_TatilSeyehatSitesi.Models
@model TableList

@foreach (var z in Model.TravelComment.OrderByDescending(x => x.DATE))
{
    <ul class="comment-list">
        <h5 class="post-author_head">@z.USERNAME <a href="#" title="Posts by admin" rel="author">@z.DATE.Value.ToString("dd.MM.yyyy")</a></h5>
        <li>
            <img src="~/BlogTheme/images/avatar.png" class="img-responsive" alt="">
            <div class="desc">
                <p>@z.COMMENT</p>
            </div>
            <div class="clearfix"></div>
        </li>
    </ul>
}

Asp.Net.MVC5_TatilSeyehatSitesi/Views/Travel/Index.cshtml
@using Asp.Net.MVC5_TatilSeyehatSitesi.Models
@using PagedList.Mvc
@using PagedList
@model TableList
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<link href="~/BlogTheme/css/bootstrap.css" rel='stylesheet' type='text/css' />
<link href="~/BlogTheme/css/style.css" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!----webfonts---->
<link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
<!----//webfonts---->
<!--script-->
<script type="text/javasc  ript" src="~/BlogTheme/js/move-top.js"></script>
<script type="text/javascript" src="~/BlogTheme/js/easing.js"></script>


<div class="content">
    <div class="container">
        <div class="content-grids">
            <div class="col-md-8 content-main">
                <div class="content-grid">
                    @foreach (var x in Model.TravelList)
                    {
                        <div class="content-grid-info">
                            <img src="~/image/@x.IMAGE" alt="@x.TITLE" />
                            <div class="post-info">
                                <h4><a href="/Travel/TravelDetail/@x.ID">@x.TITLE</a>  @x.DATE.Value.ToString("dd.MM.yyyy") / @x.TBLTRAVELCOMMENTS.Count() Yorum</h4>
                                <p>@x.DESCRIPTION.Substring(0, 150)</p>
                                <a href="/Travel/TravelDetail/@x.ID"><span></span>Daha Fazla Oku</a>
                            </div>
                        </div>
                    }
                    <div style="display:flex; align-items:center; justify-content:center; width:100%; height:50px;">
                        @Html.PagedListPager(Model.TravelList, page => Url.Action("Index", new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
                    </div>
                </div>
            </div>
            <div class="col-md-4 content-right">
                <div class="recent">
                    <h3>Random Seyahat Post</h3>
                    <ul>
                        @foreach (var y in Model.TravelList.OrderBy(x => Guid.NewGuid()).Take(3))
                        {
                            <li><a href="/Travel/TravelDetail/@y.ID">@y.TITLE</a></li>
                        }
                    </ul>
                </div>
                <div class="comments">
                    <h3>Seyahat Yorumları</h3>
                    <ul>
                        @if (Model.TravelComment.Any())
                        {
                            foreach (var z in Model.TravelComment.OrderBy(x => Guid.NewGuid()).Take(3))
                            {
                                <li><a href="#">@z.USERNAME</a> on <a href="#">@z.COMMENT</a></li>
                            }
                        }
                        else
                        {
                            <li>Henüz yorum yok.</li>
                        }
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!---->

Asp.Net.MVC5_TatilSeyehatSitesi/Views/Travel/TravelDetail.cshtml
@using Asp.Net.MVC5_TatilSeyehatSitesi.Models
@model TableList

@{
    ViewBag.Title = "TravelDetail";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/toastr.min.css" />
<script src="~/Scripts/toastr.min.js"></script>
<link href="~/BlogTheme/css/bootstrap.css" rel='stylesheet' type='text/css' />
<link href="~/BlogTheme/css/style.css" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!----webfonts---->
<link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
<!----//webfonts---->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<!--end slider -->
<!--script-->
<script type="text/javascript" src="~/BlogTheme/js/move-top.js"></script>
<script type="text/javascript" src="~/BlogTheme/js/easing.js"></script>
<!---header---->
<!--/header-->
<div class="single">
    <div class="container">
        <div class="col-md-8 single-main">
            @foreach (var x in Model.Travel)
            {
                <div class="single-grid">
                    <img src="~/image/@x.IMAGE" alt="@x.TITLE" />
                    <h2>
                        @x.TITLE
                    </h2>
                    <p>
                        @x.DESCRIPTION
                    </p>
                </div>
            }
            @Html.Action("Comments", "Travel")
            <div class="content-form">
                <h3>Yorum Yazın</h3>
                @Html.Action("Comment", "Travel")
            </div>
        </div>

        @Html.Action("TravelRightSideBar", "Travel")
    </div>
</div>
<!---->
@if (TempData["success"] != null)
{
    <script>
        toastr["success"]("@TempData["success"]")
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

@if (TempData["error"] != null)
{
    <script>
        toastr["error"]("@TempData["error"]")
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

Asp.Net.MVC5_TatilSeyehatSitesi/Views/Travel/TravelRightSideBar.cshtml
@using Asp.Net.MVC5_TatilSeyehatSitesi.Models
@model TableList
<div class="col-md-4 side-content">
    <div class="recent">
        <h3>Random Post</h3>
        <ul>
            @foreach (var y in Model.Travel.OrderBy(x => Guid.NewGuid()).Take(3))
            {
                <li><a href="/Travel/TravelDetail/@y.ID">@y.TITLE</a></li>
            }
        </ul>
    </div>
    <div class="comments">
        <h3>Seyahat Yorumları</h3>
        <ul>
            @if (Model.TravelComment.Any())
            {
                foreach (var z in Model.TravelComment.OrderBy(x => Guid.NewGuid()).Take(3))
                {
                    <li><a href="#">@z.USERNAME</a> on <a href="#">@z.COMMENT</a></li>
                }
            }
            else
            {
                <li>Henüz yorum yok.</li>
            }
        </ul>
    </div>
</div>
<div class="clearfix"></div>